org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


minecraft_version=1.20.1
jei_version=15.2.0.27
geckolib_version=4.4.6
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.5
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1


mod_id=lostriver
mod_name=Lost River
mod_license=MIT
mod_version=1.0.0-beta4
mod_group_id=su.sonoma
mod_authors=SaddyDEAD
mod_description=Lost River - Subnautica mod
