org.gradle.jvmargs=-Xmx4g
org.gradle.parallel=true
org.gradle.caching=true


neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
minecraft_version=1.21.1
jei_version=19.21.1.248
geckolib_version=4.7.3
customportalapi_version=1.0.11
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.115
neo_version_range=[21.1.0,)
loader_version_range=[5.6,)
kotlinforforge_version=5.7.0


mod_id=lostriver
mod_name=Lost River
mod_license=MIT
mod_version=1.0.0-beta6
mod_group_id=su.sonoma
mod_authors=SaddyDEAD, Zvov14, Ktlo
mod_description=Lost River - Subnautica mod
