name: Modrinth

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Modrinth Release
        uses: dsx137/modrinth-release-action@main
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        with:
          name: Lost River
          project_id: LgNfX8cW
          loaders: forge
          game_versions: 1.20.1 # 1.12.2:1.20.6 means version range
          version_number: 1.0.0-alpha
          files: |
            ./build/libs/lostriver-1.0.0-alpha.jar
          dependencies: 8BmcQJ2H:required, ordsPcFz:required
          changelog: ${{ github.event.release.body }}
          version_type: alpha # or beta, alpha
          featured: false
          status: 'draft' # or archived, draft, unlisted, scheduled, unknown
          requested_status: 'draft' # or archived, draft, unlisted
          updatable: false # default true, means updating existing version
          delete_old_files: false # default true