name: Modrinth

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: LgNfX8cW
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            build/libs/lostriver-${{ github.event.release.tag_name }}.jar

          loaders: |
            forge

          name: Lost River
          version: ${{ github.event.release.tag_name }}
          version-type: alpha
          changelog-file: ${{ github.event.release.body }}

          game-versions: |
            1.20.1

          dependencies: |
            kotlinforforge(required){modrinth:ordsPcFz}
            geckolib(required){modrinth:8BmcQJ2H}